### ISSUE TITLE
Smart chat colors only appearing while focused in respective chat, not public

### ISSUE THREAD

**Issue by Bass-Music** [MarbleTurtle/Color-Coordinator#16]
Plug-in has worked beautifully for me and I recommend it to many people. Thanks for all your work. 

Today while swapping between chat box modes to explain functionality to someone, I typed in /@p for the first time to disable auto chatbox - for example instead of /c changing all typed messages regardless of channel to clan chat, it types in the opened tab chat. Now, when I type by pressing enter in public it will say “press enter to type (clan chat)” but type in the default public blue color.

 If I click on the clan chat it will type in the appropriate custom color. Also if I enter the command /c // for clan or /f // friends etc., then type it will also appear in the appropriate color. I’ve turned the autochatbox on and off, uninstalled and reinstalled plug-in, turned it on and off and tried various combinations of commands and chatbox settings but it hasn’t resolved. 
 
I have a feeling I’m missing something about the autochatbox functionality because this was the first time using /@ commands but unsure. 

Appreciate any help!

**Comment by Bass-Music** [comment]
Correction: 
It actually types in the color of the opened chat panel, even if the chat the message will go to is another color

Types Pink, but clan chat enabled; friends chat color pink
![image](https://github.com/user-attachments/assets/6e529b6e-5c95-47b9-ac8b-c38494d074ac)

![image](https://github.com/user-attachments/assets/7860a1be-66b1-44a6-85a2-5b1589b8cfb3)

Clan chat enabled so it should type in the green as it does while clan chat window is open
![image](https://github.com/user-attachments/assets/4fa8f442-2404-4a03-adbc-4908e6cc5b3f)

**Comment by ririshi** [comment]
Thank you for the report and the details. I recently released 1.5.1 which most likely introduces a bug because of a string split that should've been returning 2 instead of one single string (a little mistake in my understanding of the function). I think it causes the plugin to disregard the currently active chat mode (i.e. setting your chat mode with `/@`. I'll try to get a bug fix released as soon as possible.

**Comment by ririshi** [comment]
1.5.2 was released and should fix this issue.

**Comment by Bass-Music** [comment]
Thanks so much!
