### ISSUE TITLE
Ironman icons gone

### ISSUE THREAD

**Issue by Fwsh** [MarbleTurtle/Color-Coordinator#17]
Recently, ironman icons have been disappearing while this plugin is active. The icon is supposed to be on the left of the username in the text input area, but it goes away while using the plugin. The icon reappears when disabling it. I've only tested it with my regular ironman and my HCGIM, so I'm not sure if it affects other iron types, but I'd assume so.

It's not an urgent issue, but I must admit I got a little spooked when I logged in to my HCGIM and saw my icon was gone lol.

**Comment by ririshi** [comment]
Thank you for the report. I'm very sorry for the inconvenience. There is a bugfix being rolled out in 1.5.2, currently awaiting approval of the RL team.

**Comment by ririshi** [comment]
1.5.2 got released today and should fix this bug.
