### ISSUE TITLE
Input color isn't immediately set after pressing enter with Key Remapping enabled

### ISSUE THREAD

**Issue by ririshi** [MarbleTurtle/Color-Coordinator#4]
When the Key Remapping plugin is reset, the chatbox has no keyboard focus by default. Pressing enter enables chat input, but the chat input is colored default blue until one starts typing (or presses a modifier key like shift or control), regardless of what channel the user is currently in. I would prefer to immediately see a green star after pressing enter, when in the clan chat tab or in `/c` chat mode.

**Comment by ashtonyoung** [comment]
Along with this, it is confusing to have this plugin with Key Remapping enabled also. It no longer shows "Press Enter to Chat..." in the textbox when this plugin is enabled. I like the idea of this plugin, however, I currently have it off due to this.

**Comment by russel204** [comment]
I actually came here to report the same thing as Ashton. I love the plugin but if it could keep the "Press Enter to Chat..." that would be really appreciated

**Comment by ririshi** [comment]
This was fixed by #9.
