### ISSUE TITLE
Guest clan color is same as regular clan

### ISSUE THREAD

**Issue by pwatts6060** [MarbleTurtle/Color-Coordinator#6]
https://i.gyazo.com/18a9457b041ac73ea25aa2c02f8816da.gif 

two // is dark red which is correct for my clan chat. three /// is the same color though for guest chat when it should really be green I think.

**Comment by ririshi** [comment]
Since the latest update, this should work correctly. In my tests, // is green, while /// is blue, just like my in-game color settings. Let me know if it's still an issue.
